project:
  type: website
  output-dir: .
  pre-render:
    - scripts/pre_create_papers_file.py
   # - scripts/pre_check_skierg_records.py
    - scripts/pre_doi_from_rogue_scholar.py
    - scripts/pre_canonicalise_tags.py
python:
  path: "/Users/ck/.virtualenvs/r-reticulate/bin/python"
resources:
  - CNAME

website:
  title: "Chandan Kumar"
  description: "Chandan Kumar is a computational scientist/data scientist working at the intersection of AI, Deep Learning and Computer Vision."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: papers
        text: Papers
      # - href: teaching
      #   text: Teaching
      - href: cv
        text: CV
      # - href: media
      #   text: Media
      - href: posts
        text: My Notes
      #- href: cv_test
      #  text: test
      # - href: https://computationalinfectiousdisease.com
      #   text: My book
  page-footer:
    left: "(c) Chandan Kumar, 2023–. [Disclaimer](disclaimer)"
  twitter-card: true
  open-graph: true
  google-analytics: ""

format:
  html:
    theme: default
      #- cosmo
     # - custom.scss
    toc: true
    toc_depth: 3
    toc_float: true
    toc_smooth_scroll: true
    toc_highlight: true
    fig-align: center




